"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderNavBar from './components/HeaderNavBar'
import React, { useEffect, useState } from 'react';
import { UserLocationContext } from '@/context/UserLocationContext';

// can change font here
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const [userLocation, setUserLocation] = useState([]);

  useEffect(() => {
    getUserLocation()
  }, []);

  // gets currnet location of user
  const getUserLocation = () => {
    navigator.geolocation.getCurrentPosition((pos) => {
      console.log(pos)
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })
    })
  }


  return (
    <html lang="en">
      <UserLocationContext.Provider value={{userLocation, setUserLocation}}>
        <HeaderNavBar />
        <body >{children}</body>

      </UserLocationContext.Provider>

    </html>
  )
}
